SWYP6-Team7/backend

src/main/java/swyp/swyp6_team7/Swyp6Team7Application.java, src/main/java/swyp/swyp6_team7/global/config/QuerydslConfig.java, src/main/java/swyp/swyp6_team7/travel/controller/TravelHomeController.java, src/main/java/swyp/swyp6_team7/travel/domain/Travel.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelRecentDto.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelRecentResponse.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepository.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/travel/service/TravelHomeService.java, src/test/java/swyp/swyp6_team7/config/DataConfig.java, src/test/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImplTest.java
feat: 지금 참가 가능한 여행 콘텐츠 #9
* 최근 발행된 여행 콘텐츠 목록을 페이징해서 가져오는 기능 및 api 구현
* Qurydsl의 transform과 페이징을 함께 적용하니 오류가 발생하는 문제가 있었다.
* 콘텐츠에 태그가 여러 개 달린 경우 페이징 할 때는 여러 개의 데이터라고 판단되지만, 전송할 때에는 group으로 묶기 때문에 발생하는 문제라고 파악했다.
* 우선 전달한 여행 콘텐츠 식별자 리스트를 먼저 생성하고, 해당 식별자에 대해 join 등을 사용해 데이터를 만드는 방식으로 구현했다. -> 추후 시간이 남을 경우 보완 및 리팩토링 할 예정
=> feat: 지금 참가 가능한 여행 콘텐츠 목록

src/main/java/swyp/swyp6_team7/travel/dto/TravelSearchCondition.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelSearchDto.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepository.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/travel/service/TravelService.java, src/test/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImplTest.java
feat: 여행 콘텐츠 검색 기능 태그 필터링 #13
여행 콘텐츠를 검색하는 기능에 태그 필터링 로직을 추가함
* TravelCustomRepository의 search 메서드 반환값을 TravelSearchDto로 수정
* TravelSearchDto의 from 메서드 삭제
* TravelSearchCondition의 Builder를 클래스 레벨로 지정 후 tags 디폴트값 설정
* TravelCustomRepositoryImpl search 메서드 로직 수정
* where 절에 eqTags 추가, having 절로 모든 태그 존재 여부 확인
* 태그 필터링 테스트코드 추가
.
=> feat: 여행 콘텐츠 검색 - 태그 필터링

build.gradle, src/main/java/swyp/swyp6_team7/travel/controller/TravelController.java, src/main/java/swyp/swyp6_team7/travel/domain/GenderType.java, src/main/java/swyp/swyp6_team7/travel/domain/PeriodType.java, src/main/java/swyp/swyp6_team7/travel/domain/Travel.java, src/main/java/swyp/swyp6_team7/travel/domain/TravelStatus.java, src/main/java/swyp/swyp6_team7/travel/dto/TravelSearchCondition.java, src/main/java/swyp/swyp6_team7/travel/dto/request/TravelCreateRequest.java, src/main/java/swyp/swyp6_team7/travel/dto/request/TravelUpdateRequest.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelDetailResponse.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelRecentDto.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelSearchDto.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImpl.java, src/test/java/swyp/swyp6_team7/travel/controller/TravelControllerTest.java, src/test/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImplTest.java
feat: 여행 콘텐츠 데이터 및 CRUD 수정 #17 
- Travel 도메인 필드 변경
- 기간, 성별의 경우 Enum으로 관리
- 기획에서 제외된 필드 삭제
- 변경된 도메인에 맞춰 DTO 및 테스트 코드 수정
- 이외의 사소한 오류 수정
- Response 과정에서 더미데이터로 고정해두었던 userName에 실제 사용자 이름이 들어가도록 수정
- search 과정에서 Request param의 tags가 null일 때 발생하던 오류를 수정
- 지금 참가 가능한 콘텐츠 조회에서 상태가 IN_PROGRESS인 경우만 가져오도록 수정
.
=> feat: Travel 도메인 및 기획 변경 사항 반영

src/main/java/swyp/swyp6_team7/travel/controller/TravelController.java, src/main/java/swyp/swyp6_team7/travel/dto/TravelSearchCondition.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/travel/util/TravelSearchConstant.java, src/test/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImplTest.java
feat: 여행 콘텐츠 검색 필터링 - 성별, 인원, 기간 #20
여행콘텐츠 검색 중 성별, 인원, 기간 필터링 기능을 추가함
- TravelSearchConstant: 콘텐츠 검색에 필요한 상수들을 관리하기 위해 클래스 추가함
- TravelSearchConditon: 각 조건 리스트가 null인 경우 빈 리스트로 설정되도록 수정 및 적절히 가공
- TravelController: 변경된 TravelSearchCondition 생성 로직에 맞춰 수정
- TravelCustomRepositoryImpl: 각 조건 필터링을 위해 BooleanExpression 생성 메서드를 추가, 테스트코드 작성
.
=> feat: 여행콘텐츠 검색 성별, 인원, 기간 필터링 추가

src/main/java/swyp/swyp6_team7/travel/util/TravelRecommendComparator.java, src/test/java/swyp/swyp6_team7/travel/util/TravelRecommendComparatorTest.java
feat: 추천 여행 콘텐츠 목록 #18
메인 페이지의 추천 여행 콘텐츠 목록 api의 마지막 정렬 조건을 추가했다.
공통태그 개수가 많은 순서 -> 마감날짜가 가까운 순서 -> 제목 가나다순서
총 3가지의 기준으로 정렬을 진행하게 된다.
.
=> feat(travel): 여행콘텐츠 추천목록 가나다순 정렬 추가

src/main/java/swyp/swyp6_team7/Swyp6Team7Application.java, src/main/java/swyp/swyp6_team7/enrollment/dto/EnrollmentResponse.java, src/main/java/swyp/swyp6_team7/enrollment/service/EnrollmentService.java, src/main/java/swyp/swyp6_team7/notification/controller/NotificationController.java, src/main/java/swyp/swyp6_team7/notification/dto/NotificationDto.java, src/main/java/swyp/swyp6_team7/notification/dto/TravelNotificationDto.java, src/main/java/swyp/swyp6_team7/notification/entity/Notification.java, src/main/java/swyp/swyp6_team7/notification/entity/NotificationType.java, src/main/java/swyp/swyp6_team7/notification/entity/TravelNotification.java, src/main/java/swyp/swyp6_team7/notification/repository/NotificationRepository.java, src/main/java/swyp/swyp6_team7/notification/service/NotificationService.java, src/main/java/swyp/swyp6_team7/notification/util/NotificationMaker.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelDetailResponse.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelRecentDto.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelRecommendResponse.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelSearchDto.java
.
여행 참가 신청, 수락, 거절 작업이 발생할 때 정해진 포맷의 알림을 생성해 저장한다
알림 조회 기능
사용자가 자신의 알림 목록을 조회할 때 페이징을 적용해 10개씩 알림을 보여준다
사용자가 조회가 발생하면 알림의 read 여부를 true로 변경한다
여행 알림의 경우 어떤 여행에 대한 알림인지 추가적인 정보가 필요하다
또한 향후 추가될 가능성이 있는 댓글 알림을 고려해 알림 엔티티는 Notification 추상 클래스로 구현했으며
단순 목록 조회가 주요 기능임을 고려해 JPA 단일 테이블 전략을 선택했다.
.
=> feat: 참가 신청 관련 알림 생성 및 목록 조회 기능

src/main/java/swyp/swyp6_team7/bookmark/repository/BookmarkRepository.java, src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentRepository.java, src/main/java/swyp/swyp6_team7/travel/controller/TravelController.java, src/main/java/swyp/swyp6_team7/travel/domain/TravelStatus.java, src/main/java/swyp/swyp6_team7/travel/dto/TravelDetailDto.java, src/main/java/swyp/swyp6_team7/travel/dto/TravelRecommendDto.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelDetailResponse.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelRecentDto.java, src/main/java/swyp/swyp6_team7/travel/dto/response/TravelSearchDto.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepository.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/travel/service/TravelService.java, src/test/java/swyp/swyp6_team7/travel/controller/TravelControllerTest.java, src/test/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImplTest.java, src/test/java/swyp/swyp6_team7/travel/service/TravelListServiceTest.java, src/test/java/swyp/swyp6_team7/travel/service/TravelServiceTest.java
feat: 여행 조회 관련 기능에 신청/모집 적용 #33
여행 콘텐츠 상세 조회 정보에 신청수, 관심수, 주최여부, 신청 가능 여부를 추가함
querydsl에서 여행 및 주최 정보를 가져올 때만 사용할 목적으로 TravelDetailDto를 추가함
기존의 TravelDetailResponse는 TravelDetailDto에 신청수, 관심수, 주최여부, 신청 가능 여부가 추가되는 형태
여행 목록 조회 계열 기능에 현재 모집완료된 인원 정보가 제대로 들어가도록 더미 데이터를 삭제하고 수정함
querydsl에서 Travel companions 리스트의 size를 함께 가져오도록 DTO를 수정함
.
=> feat: 여행 조회 기능 수정

src/main/java/swyp/swyp6_team7/Swyp6Team7Application.java, src/main/java/swyp/swyp6_team7/notification/repository/NotificationRepository.java, src/main/java/swyp/swyp6_team7/notification/service/NotificationService.java, src/test/java/swyp/swyp6_team7/notification/repository/NotificationRepositoryTest.java
Notification 목록 조회에 사용하는 Repository 메서드를 수정함
isRead 값이 false인 Notification이 앞쪽 페이지에 위치하도록 Order by 조건을 추가.
isRead에 대해 Asc, createdAt에 대해 desc를 수행함
`Page<Notification> getNotificationsByReceiverNumberOrderByIsReadAscCreatedAtDesc(int userNumber, Pageable pageable);`
=> feat: Notification 목록 조회 정렬 수정

src/main/java/swyp/swyp6_team7/companion/domain/Companion.java, src/main/java/swyp/swyp6_team7/enrollment/domain/Enrollment.java, src/main/java/swyp/swyp6_team7/enrollment/service/EnrollmentService.java, src/main/java/swyp/swyp6_team7/notification/entity/Notification.java, src/main/java/swyp/swyp6_team7/notification/entity/NotificationMessageType.java, src/main/java/swyp/swyp6_team7/notification/entity/TravelNotification.java, src/main/java/swyp/swyp6_team7/notification/service/NotificationService.java, src/main/java/swyp/swyp6_team7/notification/util/NotificationMaker.java, src/main/resources/application.yml
.
- 여행 참가 신청 기능에서 참가 신청이 발생할 때 주최자, 신청자 모두에게 알림이 생성되도록 EnrollmentService를 수정함
- NotificationService 메서드 추가
- createEnrollNotificatonToHost()는 주최자가 수신하는 알림 생성
- createEnrollNotification()는 신청자가 수신하는 알림 생성
- NotificationMessageType Enum 클래스에서 notification의 content를 생성하도록 수정
- `public abstract String getContent(String travelTitle)` 추가
- 각 Enum 타입에 따라 getContent 함수를 실행해 content를 가져올 수 있다
.
=> feat: 여행 참가 신청 기능에서 신청자도 알림을 받을 수 있도록 수정

src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentRepository.java, src/main/java/swyp/swyp6_team7/enrollment/service/EnrollmentService.java, src/main/java/swyp/swyp6_team7/travel/controller/TravelEnrollmentController.java
.
- 특정 여행에 대한 enrollment 목록 조회 로직 수정
- 기존: status에 상관없이 찾은 enrollment를 전달
- 현재: status가 PENDING(대기) 상태인 enrollment만 전달
- 특정 여행에 대한 PENDING 상태의 신청서 개수를 전달하는 GET 요청 추가
- `/api/travel/{travelNumber}/enrollmentCount`
.
=> fix: enrollment 목록 조회 로직 수정

src/main/java/swyp/swyp6_team7/comment/controller/CommentController.java, src/main/java/swyp/swyp6_team7/comment/service/CommentService.java, src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentCustomRepository.java, src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/enrollment/service/EnrollmentService.java, src/main/java/swyp/swyp6_team7/notification/entity/Notification.java, src/main/java/swyp/swyp6_team7/notification/entity/NotificationMessageType.java, src/main/java/swyp/swyp6_team7/notification/entity/TravelNotification.java, src/main/java/swyp/swyp6_team7/notification/service/NotificationService.java, src/main/java/swyp/swyp6_team7/notification/util/NotificationMaker.java
.
여행 콘텐츠에 댓글이 추가될 경우 Notification알림을 생성한다
- 알림 수신자: 여행 주최자, 여행 신청자
- 알림 title: `멤버 댓글 알림`
- 주최자 content: `개설하신 [여행title]에 멤버 댓글이 달렸어요. 확인해보세요.`
- 신청자 content: `참가 신청하신 [여행title]에 멤버 댓글이 달렸어요. 확인해보세요.`
구현 관련 사항
- 댓글 알림은 여행 신청/수락 알림과는 달리 추가적인 데이터가 필요하지 않음
- 추상 클래스로 설정한 Notification을 일반 클래스로 변경함
- Notification, TravelNotification의 `@Builder`를 `@SuperBuilder` 어노테이션으로 변경함
- 댓글 추가에 대한 알림 생성 작업은 NotificationService에서 비동기로 처리하도록 설정
- 특정 여행에 대해 PENDING, ACCEPTED 상태인 Enrollment의 userNumber 목록을 가져온다
- 각 userNumber에 대해 Notification을 생성해 저장한다
.
=> feat: 여행콘텐츠 댓글 생성 알림

.github/workflows/deploy.yml
.
* main 브랜치에 merge하는 과정에서 아래의 오류가 발생해 merge가 fail하는 문제
&nbsp;
* Build 할 때 Permission을 허용하는 코드를 추가함
```
- name: Test and Build
run: |
chmod +x ./gradlew
./gradlew clean build
```
.
=> fix(deploy): Github Actions Build Permission 설정 추가

src/main/java/swyp/swyp6_team7/image/controller/ImageProfileController.java, src/main/java/swyp/swyp6_team7/image/dto/request/ImageCreateRequestDto.java, src/main/java/swyp/swyp6_team7/image/dto/request/TempDeleteRequestDto.java, src/main/java/swyp/swyp6_team7/image/dto/request/TempUploadRequestDto.java, src/main/java/swyp/swyp6_team7/image/s3/S3Uploader.java, src/main/java/swyp/swyp6_team7/image/service/ImageCommunityService.java, src/main/java/swyp/swyp6_team7/image/service/ImageProfileService.java, src/main/java/swyp/swyp6_team7/image/service/ImageService.java, src/main/java/swyp/swyp6_team7/image/util/S3KeyHandler.java, src/main/java/swyp/swyp6_team7/image/util/StorageNameHandler.java
- [V] 새로운 기능 추가
- [V] 버그 수정
fix:커뮤니티 이미지 정식 저장 안됨 오류 수정 / feat: 프로필 이미지 임시저장 기능 추가
커뮤니티 이미지 정식 저장 안됨 오류 수정
-> 조회 업데이트에서 빈 배열 선언 시 사이즈가 0인 배열 선언해서 배열에 데이터 담을때 index 0 에러 발생해서 rollback 되는 오류 였음
프로필 이미지 임시저장 기능 추가
=> fix:커뮤니티 이미지 정식 저장 안됨 오류 수정 / feat: 프로필 이미지 임시저장 기능 추가

src/main/java/swyp/swyp6_team7/image/controller/ImageProfileController.java, src/main/java/swyp/swyp6_team7/image/dto/response/ImageTempResponseDto.java, src/main/java/swyp/swyp6_team7/image/service/ImageProfileService.java, src/main/java/swyp/swyp6_team7/image/service/ImageService.java
- [V] 버그 수정
임시 저장 시 response 문자열 깨짐 문제 해결
프로필 이미지 임시저장 response dto에 담기
=> fix:프로필 이미지 임시저장 response dto에 담기

src/main/java/swyp/swyp6_team7/enrollment/dto/EnrollmentResponse.java, src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentCustomRepositoryImpl.java
.
* 여행 콘텐츠 신청 목록 조회 기능 수정
* 기존의 신청자 관련 데이터(userNumber, userAgeGroup)에 사용자 프로필(profileUrl) 추가함
* `EnrollmentCustomRepositoryImpl`의 `findEnrollmentsByTravelNumber` 로직 수정
* PENDING 상태의 신청서를 조회하는 메서드이다
* Image 테이블을 left join해 3가지 조건을 만족하는 데이터에 대해 image.url을 가져온다
```
.leftJoin(image).on(enrollment.userNumber.eq(image.relatedNumber)
.and(image.relatedType.eq("profile"))
.and(image.order.eq(0)))
```
=> feat(enrollment): 신청목록 조회DTO 사용자 프로필 url 추가

src/main/java/swyp/swyp6_team7/companion/dto/CompanionInfoDto.java, src/main/java/swyp/swyp6_team7/companion/repository/CompanionCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/companion/service/CompanionService.java
.
* 여행 콘텐츠 동행자 목록 조회 기능 수정
* `CompanionInfoDto`에 사용자 프로필 url 필드(profileUrl) 추가
* 기존: 각 사용자에 대해 userNumber, userName, ageGroup
* 현재: 기존 데이터에 사용자 프로필 url String 추가
* `CompanionCustomRepositoryImpl` 수정
* `findCompanionInfoByTravelNumber` 메서드에서 Image 테이블 left join 후 image.url을 가져온다
```
.leftJoin(image).on(companion.userNumber.eq(image.relatedNumber)
.and(image.relatedType.eq("profile")).and(image.order.eq(0)))
```
=> feat(companion): 여행 동행 목록 조회 사용자 프로필 url 추가

src/main/java/swyp/swyp6_team7/companion/dto/CompanionInfoDto.java, src/main/java/swyp/swyp6_team7/companion/repository/CompanionCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/companion/service/CompanionService.java
.
* main에 잘못 merge해서 Revert했는데, develop까지 Rervert되어 새로운 branch에 코드 작성함
* 여행 콘텐츠 동행자 목록 조회 기능 수정
* `CompanionInfoDto`에 사용자 프로필 url 필드(profileUrl) 추가
* 기존: 각 사용자에 대해 userNumber, userName, ageGroup
* 현재: 기존 데이터에 사용자 프로필 url String 추가
* `CompanionCustomRepositoryImpl` 수정
* `findCompanionInfoByTravelNumber` 메서드에서 Image 테이블 left join 후 image.url을 가져온다
```
.leftJoin(image).on(companion.userNumber.eq(image.relatedNumber)
.and(image.relatedType.eq("profile")).and(image.order.eq(0)))
.
=> feat(companion): 여행 동행자 조회 시 프로필 image url 추가

src/main/java/swyp/swyp6_team7/tag/service/TravelTagService.java, src/main/java/swyp/swyp6_team7/travel/controller/TravelController.java, src/main/java/swyp/swyp6_team7/travel/controller/TravelHomeController.java, src/main/java/swyp/swyp6_team7/travel/controller/TravelSearchController.java, src/main/java/swyp/swyp6_team7/travel/domain/Travel.java, src/main/java/swyp/swyp6_team7/travel/dto/TravelRecommendDto.java, src/main/java/swyp/swyp6_team7/travel/dto/TravelSearchCondition.java, src/main/java/swyp/swyp6_team7/travel/dto/request/TravelCreateRequest.java, src/main/java/swyp/swyp6_team7/travel/dto/request/TravelUpdateRequest.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/travel/repository/TravelRepository.java, src/main/java/swyp/swyp6_team7/travel/service/TravelHomeService.java, src/main/java/swyp/swyp6_team7/travel/service/TravelSearchService.java, src/main/java/swyp/swyp6_team7/travel/service/TravelService.java, src/test/java/swyp/swyp6_team7/companion/service/CompanionServiceTest.java, src/test/java/swyp/swyp6_team7/enrollment/controller/EnrollmentControllerTest.java, src/test/java/swyp/swyp6_team7/tag/service/TagServiceTest.java, src/test/java/swyp/swyp6_team7/tag/service/TravelTagServiceTest.java, src/test/java/swyp/swyp6_team7/travel/controller/TravelControllerTest.java, src/test/java/swyp/swyp6_team7/travel/controller/TravelEnrollmentControllerTest.java, src/test/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImplTest.java, src/test/java/swyp/swyp6_team7/travel/repository/TravelRepositoryTest.java, src/test/java/swyp/swyp6_team7/travel/service/TravelHomeServiceTest.java, src/test/java/swyp/swyp6_team7/travel/service/TravelServiceTest.java
refactor: 여행 관련 기능 리팩토링 #136
Travel CRUD, Home, Search와 관련된 기능을 리팩토링하고 테스트코드, 로그를 추가함
- 로그인 사용자의 번호를 Controller단에서 가져와 메서드를 통해 넘겨주는 방식으로 통일함
- Service 테스트가 용이해짐
- 각 기능에 대해 Service, Repository 테스트 코드 수정 및 추가
- 기존에 작성되어 있던 테스트코드를 검토 및 수정 완료
- `TravelCustomRepositoryImpl` 테스트코드 재작성
- Travel 생성 로직 수정
- DTO에서 엔티티를 생성하는 방식을 static 메서드를 통해 Travel에서 객체를 생성하도록 수정함
- 여행 생성 시 TravelTag를 따로 생성해서 저장하는 방식을 JPA 연관 관계를 고려한 방식으로 수정함
.
=> refactor: Travel CRUD, Home, Search 관련 기능 리팩토링

src/main/java/swyp/swyp6_team7/bookmark/repository/BookmarkRepository.java, src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentCustomRepository.java, src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/notification/dto/TravelNotificationDto.java, src/main/java/swyp/swyp6_team7/notification/entity/NotificationMessageType.java, src/main/java/swyp/swyp6_team7/notification/entity/TravelNotification.java, src/main/java/swyp/swyp6_team7/notification/service/NotificationService.java, src/main/java/swyp/swyp6_team7/notification/util/NotificationMaker.java, src/test/java/swyp/swyp6_team7/bookmark/repository/BookmarkRepositoryTest.java, src/test/java/swyp/swyp6_team7/config/SyncTaskExecutor.java, src/test/java/swyp/swyp6_team7/config/SynchronousTaskExecutorConfig.java, src/test/java/swyp/swyp6_team7/enrollment/repository/EnrollmentCustomRepositoryImplTest.java, src/test/java/swyp/swyp6_team7/notification/controller/NotificationControllerTest.java, src/test/java/swyp/swyp6_team7/notification/service/NotificationServiceTest.java
feat: 여행 참가 인원 마감 알림 #143
* 인원 마감 알림 수신자 대상 추가
- 기존: 주최자, 참가 확정자(companion)
- 현재: 주최자, 참가 확정자 + pending상태의 신청자, 해당 여행에 즐겨찾기(북마크) 한 사용자
- 즐겨찾기 사용자의 경우, 주최자/참가확정자/신청자인 경우를 제외해 중복 알림을 방지함
* NotificationService 테스트코드 작성
- `@Async` 메서드를 테스트하기 위해 테스트 Config 디렉토리에 `SynchronousTaskExecutorConfig` 추가
* NotificationMaker 여행 알림 주최자용, 일반용 메서드 분리
- 주최자용: receiverNumber가 여행의 userNumber, travelHost의 값이 true
=> feat: 여행 인원 마감 알림 수신 대상 추가

src/main/java/swyp/swyp6_team7/auth/service/KakaoService.java
> #5 
> 카카오 로그인 시 사용자의 이메일을 받기 전 임시로 unkwown@example.com값이 들어가지만 이 값이 Unique 제약조건에 걸리기 때문에 이메일에 대한 임시값을 다음과 같이 변경함.
"unknown@" + UUID.randomUUID().toString().substring(0, 8) + ".email"
=> refactor: 카카오 로그인 시 이메일 임시 값에 랜덤한 문자열 추가

src/main/java/swyp/swyp6_team7/category/intializer/CategoryInitializer.java, src/main/java/swyp/swyp6_team7/community/controller/CommunityController.java, src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepository.java, src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepositoryImpl.java, src/main/java/swyp/swyp6_team7/community/service/CommunityListService.java
> 
- "전체" 카테고리 요청 처리 로직 추가
- service 계층에서 categoryNumber가 null일 경우 전체 게시물을 검색하도록 처리
- CommunityCustomRepository에 searchWithoutCategory 메서드 추가
- 카테고리 필터 없이 모든 게시물을 검색
- 기존 검색 로직과 동일하게 키워드, 좋아요 수 등 조건 적용
- Controller에서 categoryName="전체"를 인식하고 categoryNumber를 null로 전달하도록 수정
- 기존 로직과의 호환성을 유지하며 모든 게시물 조회 가능
=> feat: 커뮤니티 "전체" 카테고리 요청 처리 로직 추가

src/test/java/swyp/swyp6_team7/bookmark/controller/BookmarkControllerTest.java, src/test/java/swyp/swyp6_team7/profile/controller/ProfileControllerTest.java, src/test/java/swyp/swyp6_team7/travel/controller/TravelAppliedControllerTest.java, src/test/java/swyp/swyp6_team7/travel/controller/TravelListControllerTest.java
> #160 #154 
- 기존 jwtProvider를 사용하여 사용자 번호를 Mocking하던 부분을 MemberAuthorizeUtil.getLoginUserNumber로 변경
- mockStatic(MemberAuthorizeUtil.class) 적용하여 정적 메서드 Mocking
- 테스트 범위 내에서 MockedStatic이 유효하도록 try-with-resources 구조 적용
- @AfterEach를 사용해 테스트 독립성 보장
=> test: MemberAuthorizeUtil 기반으로 사용자 번호 Mocking

src/main/java/swyp/swyp6_team7/comment/controller/CommentController.java, src/main/java/swyp/swyp6_team7/comment/service/CommentService.java, src/main/java/swyp/swyp6_team7/community/controller/CommunityController.java
> #154 #160 
작업 내용
- categoryName의 기본값 설정
- categoryName의 기본값을 "전체"로 설정하여 커뮤니티 목록 조회 시 400 오류 해결 시도
- IncorrectResultSizeDataAccessException 예외 처리 개선
- 댓글 조회 중 발생할 수 있는 IncorrectResultSizeDataAccessException 예외 발생 시, 요청 파라미터(relatedType, relatedNumber, userNumber)와 함께 상세 로그를 추가
- getList 및 getListPage 메서드 수정
- 댓글 목록 반환 로직을 개선:
- getList: 댓글이 없을 경우 Collections.emptyList() 반환.
- getListPage: 댓글이 없을 경우 Page.empty() 반환.
- 빈 결과를 안전하게 처리할 수 있도록 방어 코드 추가.
=> fix: categoryName 기본값 설정 및 예외 상세 로그 추가
