SWYP6-Team7/backend

- src/main/java/swyp/swyp6_team7/Swyp6Team7Application.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelController.java
- src/main/java/swyp/swyp6_team7/travel/domain/Travel.java
- src/main/java/swyp/swyp6_team7/travel/domain/TravelStatus.java
- src/main/java/swyp/swyp6_team7/travel/dto/request/TravelCreateRequest.java
- src/main/java/swyp/swyp6_team7/travel/repository/TravelRepository.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
> feat: 여행 콘텐츠 등록 기능

- .gitignore
- build.gradle
- src/main/java/swyp/swyp6_team7/global/config/QuerydslConfig.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelController.java
- src/main/java/swyp/swyp6_team7/travel/domain/Travel.java
- src/main/java/swyp/swyp6_team7/travel/dto/TravelSearchCondition.java
- src/main/java/swyp/swyp6_team7/travel/dto/response/TravelSimpleDto.java
- src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepository.java
- src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImpl.java
- src/main/java/swyp/swyp6_team7/travel/repository/TravelRepository.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
- src/test/java/swyp/swyp6_team7/config/DataConfig.java
- src/test/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImplTest.java
- src/test/resources/application.yml
- Querydsl을 적용해 검색 및 필터링 기능 구현 중
- 현재 구현된 사항: 키워드 검색, 페이징 적용, 최신순 정렬
- 추후 구현할 사항: 태그 기반 검색
.
> feat: 여행 콘텐츠 검색 기능

- src/main/java/swyp/swyp6_team7/auth/controller/LoginController.java
- src/main/java/swyp/swyp6_team7/auth/jwt/JwtFilter.java
- src/main/java/swyp/swyp6_team7/auth/service/LoginService.java
- src/main/java/swyp/swyp6_team7/member/controller/MemberController.java
- src/main/java/swyp/swyp6_team7/member/entity/UserLoginHistory.java
- src/main/java/swyp/swyp6_team7/member/entity/Users.java
- src/main/java/swyp/swyp6_team7/member/repository/UserLoginHistoryRepository.java
- src/main/java/swyp/swyp6_team7/member/service/MemberService.java
- src/main/java/swyp/swyp6_team7/member/service/UserLoginHistoryService.java
>  #4 
- [ x ] 새로운 기능 추가
- [ x ] 버그 수정
> 로그인 및 로그아웃 시간 기록 기능 추가
> 관련 메서드 및 쿼리 수정
> 기능 동작 여부 테스트 완료
> 로그인 이력 테이블에 잘 삽입되는지 봐주시면 좋겠습니다.
- [ x ] 코드가 정상적으로 컴파일되나요?
- [ x ] 테스트 코드를 통과했나요?
- [ x ] merge할 브랜치의 위치를 확인했나요?
> feat: 로그인 이력 기능 추가

- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
- [v] 코드가 정상적으로 컴파일되나요?
- [v] 테스트 코드를 통과했나요?
- [v] merge할 브랜치의 위치를 확인했나요?
> chore:Sequrity Config에 healthcheck end point 퍼미션 추가

- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
> fix:cors 버전 문제 해결

- src/main/java/swyp/swyp6_team7/companion/dto/CompanionInfoDto.java
- src/main/java/swyp/swyp6_team7/companion/repository/CompanionCustomRepository.java
- src/main/java/swyp/swyp6_team7/companion/repository/CompanionCustomRepositoryImpl.java
- src/main/java/swyp/swyp6_team7/companion/repository/CompanionRepository.java
- src/main/java/swyp/swyp6_team7/companion/service/CompanionService.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelCompanionController.java
- src/main/java/swyp/swyp6_team7/travel/dto/response/TravelCompanionResponse.java
- src/test/java/swyp/swyp6_team7/companion/service/CompanionServiceTest.java
.
여행 번호가 주어졌을 때 해당 여행 콘텐츠에 모집 완료된 Companion 목록을 조회하는 기능
각 Companion은 자신의 Users 정보 일부분을 보여준다
현재 userNumber, userName을 가져오고 있으며, 향후 UI 작업에 따라 수정 가능성 있음
.
> feat: 특정 여행에 모집 완료된 인원 목록 조회 기능

- src/main/java/swyp/swyp6_team7/comment/dto/response/CommentListReponseDto.java
- src/main/java/swyp/swyp6_team7/comment/service/CommentService.java
- src/main/java/swyp/swyp6_team7/image/domain/Image.java
- [V] 코드 리팩토링
refactor:댓글 조회시 유저 프로필 이미지 보여지게 수정
> refactor:댓글 조회시 유저 프로필 이미지 보여지게 수정

- .github/workflows/deploy.yml
.
Github Actions를 이용한 CI/CD 설정 파일 작성
.
> chore: Git Actions CI/CD 설정

- .github/workflows/deploy.yml
.
Github Actions 설정 파일 syntax 오류 수정
```
- name: Set up JDK 21
uses: actions/setup-java@v4
with:
distribution: 'temurin'
java-version: '21'
```
.
> fix(deploy): Github Actions 설정 파일 syntax 오류 수정

- src/test/java/swyp/swyp6_team7/https/HealthControllerTest.java
.
* main merge 과정에서 HealthControllerTest가 실패하는 문제
* 해당 테스트코드만 실패하므로 우선 주석 처리 후 merge 실행
.
> fix(test): main merge 빌드에서 실패하는 HealthControllerTest 주석처리

- src/main/java/swyp/swyp6_team7/image/domain/Image.java
> fix: image 엔티티 필드 수정

- src/main/java/swyp/swyp6_team7/image/controller/ImageProfileController.java
- src/main/java/swyp/swyp6_team7/image/dto/request/ImageDefaultRequestDto.java
- [V] 버그 수정
서버 에러: JSON parse error: Cannot deserialize value of type `int`from Object value(token `JsonToken.START_OBJECT`)
해결을 위해 default 이미지로 수정 시 dto로 받도록 수정
> fix : default 이미지로 수정 시 dto로 받도록 수정

- src/main/java/swyp/swyp6_team7/image/controller/ImageProfileController.java
- src/main/java/swyp/swyp6_team7/image/domain/Image.java
- src/main/java/swyp/swyp6_team7/image/dto/request/ImageDefaultRequestDto.java
- [V] 버그 수정
서버 에러: JSON parse error: Cannot deserialize value of type `int`from Object value(token `JsonToken.START_OBJECT`)
해결을 위해 default 이미지로 수정 시 dto로 받도록 수정
> default 이미지로 수정 시 dto로 받도록 수정

- src/main/java/swyp/swyp6_team7/image/service/ImageCommunityService.java
- [V] 버그 수정
정식 저장 시 삭제할 이미지가 없을 경우 발생하는 오류 수정
배열 null일 경우 for문 동작 안함 수정
배열 null 체크 추가
> fix:정식 저장 시 삭제할 이미지가 없을 경우 발생하는 오류 수정

- src/main/java/swyp/swyp6_team7/image/service/ImageCommunityService.java
- [V] 버그 수정
fix:커뮤니티 이미지 정식 저장 시 isEmpty() 추가
> fix:커뮤니티 이미지 정식 저장 시 isEmpty() 추가

- src/main/java/swyp/swyp6_team7/image/service/ImageCommunityService.java
- [V] 버그 수정
fix: 커뮤니티 이미지 정식 저장 동작 안함 오류 수정
db 업데이트 메소드 트랜젝션 어노테이션 추가
> fix: 커뮤니티 이미지 정식 저장 동작 안함 오류 수정

- src/main/java/swyp/swyp6_team7/profile/controller/PasswordController.java
- src/main/java/swyp/swyp6_team7/profile/dto/PasswordChangeRequest.java
- src/main/java/swyp/swyp6_team7/profile/dto/PasswordVerifyRequest.java
- src/main/java/swyp/swyp6_team7/profile/service/ProfileService.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelAppliedService.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelListService.java
> PasswordVerifyRequest와 PasswordChangeRequest로 Dto 분리  
> 내가 신청한 여행에 page start와 end 값 검증 추가
>
> fix: 현재 비밀번호 확인 request dto 코드 분리 및 페이지 값 검증 추가

- src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentRepository.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelRequestedController.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelRequestedService.java
> 
> 사용자가 신청한 여행 게시글 목록 조회 및 신청 취소 구현
> feat: 사용자가 참가 신청한 목록 조회 기능 구현

- src/main/java/swyp/swyp6_team7/auth/jwt/JwtFilter.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelRequestedService.java
> 
> EnrollmentStatus.PENDING 상태인 여행만 필터링하여 조회하도록 수정
> feat: 주최자가 참가 수락 전인 여행만 필터링하여 조회

- src/main/java/swyp/swyp6_team7/comment/controller/CommentController.java
- src/main/java/swyp/swyp6_team7/comment/service/CommentService.java
- [V] 버그 수정
커뮤니티 댓글 삭제 안됨 오류 수정
게시글 작성자 검증 메소드에 community 경우 추가
> fix : 커뮤니티 댓글 삭제 안됨 오류 수정

- src/main/java/swyp/swyp6_team7/likes/service/LikeService.java
- [V] 버그 수정
fix:댓글 좋아요 relatedType 검증 오류 수정
if문의 문자열 잘못 입력된 것 수정
> fix:댓글 좋아요 relatedType 검증 오류 수정

- src/main/java/swyp/swyp6_team7/community/dto/response/CommunitySearchCondition.java
- src/main/java/swyp/swyp6_team7/community/dto/response/CommunitySearchDto.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepository.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepositoryImpl.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityListService.java
- src/main/java/swyp/swyp6_team7/community/util/CommunitySearchSortingType.java
- [V] 버그 수정
커뮤니티 목록 조회 정렬안됨/페이징 안됨/썸네일 안보임 오류 수정
queryDSL 정리
> fix:커뮤니티 목록 조회 정렬안됨/페이징 안됨/썸네일 안보임 오류 수정

- src/main/java/swyp/swyp6_team7/community/service/CommunityListService.java
- src/main/java/swyp/swyp6_team7/image/service/ImageCommunityService.java
- src/main/java/swyp/swyp6_team7/image/service/ImageService.java
- [V] 버그 수정
fix:default 이미지 삭제되는 문제 수정
fix:게시물 이미지 수정 시 상태값 i 추가
> fix:게시물 이미지 수정 시 상태값 i 추가

- src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepositoryImpl.java
- [V] 버그 수정
fix:추천 순 정렬 안됨 오류 수정
> fix:추천 순 정렬 안됨 오류 수정

- src/main/java/swyp/swyp6_team7/community/service/CommunityService.java
- src/main/resources/application.yml
- [V] 버그 수정
fix:multipart파일 용량 제한 설정
fix:게시물 작성자 프로필이미지가 조회 유저 프로필 이미지로 보이는 오류 수정
> fix:multipart파일 용량 제한 설정/게시물 작성자 프로필이미지가 조회 수정

- src/main/java/swyp/swyp6_team7/community/controller/MyCommunitiesController.java
- src/main/java/swyp/swyp6_team7/community/dto/response/CommunityMyListResponseDto.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepository.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepositoryImpl.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityListService.java
- src/main/resources/application.yml
- [V] 새로운 기능 추가
chore:multipart 파일 사이즈 제한 100MB로 수정
feat:내가 작성한 커뮤니티 게시물 목록 조회 기능 추가
> feat:내가 작성한 커뮤니티 게시물 목록 조회 기능 추가

- src/main/java/swyp/swyp6_team7/companion/dto/CompanionInfoDto.java
- src/main/java/swyp/swyp6_team7/companion/repository/CompanionCustomRepositoryImpl.java
- src/main/java/swyp/swyp6_team7/companion/service/CompanionService.java
> Revert "feat(companion): 여행 동행 목록 조회 사용자 프로필 url 추가"

- src/main/java/swyp/swyp6_team7/image/controller/ImageProfileController.java
- src/main/java/swyp/swyp6_team7/image/service/ImageService.java
- [V] 버그 수정
프로필 임시저장 삭제 시 디폴트 이미지도 삭제되는 문제 수정
> fix:프로필 임시저장 삭제 시 디폴트 이미지도 삭제되는 문제 수정

- src/main/java/swyp/swyp6_team7/image/repository/ImageRepository.java
- src/main/java/swyp/swyp6_team7/travel/dto/response/TravelDetailResponse.java
- src/main/java/swyp/swyp6_team7/travel/repository/TravelCustomRepositoryImpl.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
.
여행 콘텐츠를 상세 조회 기능에 주최자 프로필 이미지를 추가함
주최자 이미지를 찾지 못할 경우 default 프로필 이미지 url을 전송
> feat: 여행 콘텐츠 상세 조회 주최자 프로필 이미지

- src/main/java/swyp/swyp6_team7/comment/service/CommentService.java
- src/main/java/swyp/swyp6_team7/enrollment/repository/EnrollmentCustomRepositoryImpl.java
- src/main/java/swyp/swyp6_team7/notification/dto/TravelCommentNotificationDto.java
- src/main/java/swyp/swyp6_team7/notification/entity/TravelCommentNotification.java
- src/main/java/swyp/swyp6_team7/notification/service/NotificationService.java
- src/main/java/swyp/swyp6_team7/notification/util/NotificationMaker.java
.
* 여행 콘텐츠 댓글 추가 알림 로직 수정
* 댓글 알림을 위한 클래스 TravelCommentNotification 및 DTO 추가
* response할 때 travelNumber를 함께 보낸다
* 댓글 알림 수신 대상자 로직 수정
* 신청이 수락된 사람에게만 전송한다
* 작성자 자신에게는 알림을 전송하지 않도록 조건을 추가 
> feat(notification): 여행 댓글 알림 로직 수정

- src/main/java/swyp/swyp6_team7/comment/service/CommentService.java
- [V] 버그 수정
fix:게시물 혹은 댓글 작성자 검증 로직 오류 수정
> fix:게시물 혹은 댓글 작성자 검증 로직 오류 수정

- src/main/java/swyp/swyp6_team7/auth/controller/LoginController.java
- src/main/java/swyp/swyp6_team7/auth/controller/LogoutController.java
- src/main/java/swyp/swyp6_team7/member/service/MemberService.java
- src/main/java/swyp/swyp6_team7/member/service/UserLoginHistoryService.java
- src/test/java/swyp/swyp6_team7/member/service/UserServiceTest.java
> 로그인/로그아웃 로깅 추가
> UserServiceTest 예외 메시지 수정
> feat: 로그인/로그아웃 로깅 추가

- build.gradle
- src/main/java/swyp/swyp6_team7/global/slack/SlackAppender.java
- src/main/resources/logback-spring.xml
- src/test/resources/application.yml
> SlackAppender 클래스는 Logback Appender를 상속받아, 로그 이벤트가 발생했을 때 특정 조건에 맞는 메시지만 슬랙에 전송할 수 있도록 구현
> WebClient를 통해 JSON 형식의 메시지를 전송
> feat: 슬랙웹훅 에러메시지 전송 구현

- src/main/java/swyp/swyp6_team7/auth/service/GoogleService.java
- src/main/java/swyp/swyp6_team7/auth/service/KakaoService.java
- src/main/java/swyp/swyp6_team7/auth/service/NaverService.java
- src/main/java/swyp/swyp6_team7/auth/service/SocialLoginService.java
- src/main/java/swyp/swyp6_team7/member/repository/UserRepository.java
> #4 
> 예외처리 및 로깅 추가
소셜 로그인 사용자 정보 중복 저장 문제  수정
> fix: 소셜 로그인 사용자 정보 중복 저장 문제 

- src/main/java/swyp/swyp6_team7/auth/service/GoogleService.java
- src/main/java/swyp/swyp6_team7/auth/service/KakaoService.java
- src/main/java/swyp/swyp6_team7/auth/service/NaverService.java
- src/main/java/swyp/swyp6_team7/member/repository/UserRepository.java
> #11 
> /api/logout 경로에  인증된 사용자만 로그아웃 요청을 보내도록 수정
> fix: 로그아웃 경로 인증 추가

- src/main/java/swyp/swyp6_team7/auth/controller/GoogleController.java
- src/main/java/swyp/swyp6_team7/auth/controller/KakaoController.java
- src/main/java/swyp/swyp6_team7/auth/controller/NaverController.java
- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
> #5 
> Ajax 호출을 통해 발생하는 리다이렉션 문제를 해결하기 위해 기존 헤더를 통해서가 아닌 JSON 형태로 반환하도록 수정
> fix: 간편로그인 redirect URL JSON 형태로 반환하도록 수정

- src/main/java/swyp/swyp6_team7/auth/controller/SocialLoginController.java
> #141 
> 소셜 로그인 시에는 재가입 제한 검증만 수행하도록 수정
> refactor: 소셜 로그인 시 재가입 제한 검증만 수행하도록 수정

- src/main/java/swyp/swyp6_team7/auth/service/GoogleService.java
- src/main/java/swyp/swyp6_team7/auth/service/KakaoService.java
> #5 
> 간편 로그인 가입 시 선호 태그 저장 로직 추가
> x
> featL 간편 로그인 가입 시 선호 태그 저장 로직 추가

- src/main/java/swyp/swyp6_team7/community/controller/CommunityController.java
- src/main/java/swyp/swyp6_team7/community/controller/MyCommunitiesController.java
- src/main/java/swyp/swyp6_team7/community/dto/response/CommunityListResponseDto.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityListService.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityService.java
> #154 
> 커뮤니티 관련 예외처리 추가 및 로깅 추가
@RequestParam과 @PathVariable에 name 속성을 명시하여 파라미터 매핑 명확화
데이터 조회 시 반환값이 없는 경우를 대비한 기본값 처리 추가
> refactor: 커뮤니티 관련 예외 처리 강화 및 로깅 추가

- src/main/java/swyp/swyp6_team7/category/domain/Category.java
- src/main/java/swyp/swyp6_team7/category/repository/CategoryRepository.java
- src/main/java/swyp/swyp6_team7/comment/controller/CommentController.java
- src/main/java/swyp/swyp6_team7/comment/dto/response/CommentDetailResponseDto.java
- src/main/java/swyp/swyp6_team7/comment/dto/response/CommentListReponseDto.java
- src/main/java/swyp/swyp6_team7/comment/service/CommentService.java
- src/main/java/swyp/swyp6_team7/community/controller/CommunityController.java
- src/main/java/swyp/swyp6_team7/community/domain/Community.java
- src/main/java/swyp/swyp6_team7/community/dto/response/CommunityDetailResponseDto.java
- src/main/java/swyp/swyp6_team7/community/dto/response/CommunityListResponseDto.java
- src/main/java/swyp/swyp6_team7/community/dto/response/CommunityMyListResponseDto.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityListService.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityService.java
- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
- src/main/java/swyp/swyp6_team7/global/exception/GlobalExceptionHandler.java
- src/main/java/swyp/swyp6_team7/likes/util/LikeStatus.java
> 
> 아래의 API들이 비로그인 사용자의 요청에 동작하도록 기능을 수정함
- 커뮤니티 목록 조회: `/api/community/posts`
- 커뮤니티 게시글 상세 조회: `/api/community/posts/{postNumber}`
- 댓글 목록 조회 : `/api/{relatedType}/{relatedNumber}/comments`
> feat: 커뮤니티 관련 비로그인 기능 구현

- src/main/java/swyp/swyp6_team7/bookmark/controller/BookmarkController.java
- src/main/java/swyp/swyp6_team7/comment/controller/CommentController.java
- src/main/java/swyp/swyp6_team7/comment/repository/CommentRepository.java
- src/main/java/swyp/swyp6_team7/comment/service/CommentService.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityRepository.java
- src/main/java/swyp/swyp6_team7/likes/controller/LikeController.java
- src/main/java/swyp/swyp6_team7/profile/controller/ProfileController.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelAppliedController.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelListController.java
- src/test/java/swyp/swyp6_team7/travel/controller/TravelAppliedControllerTest.java
- src/test/java/swyp/swyp6_team7/travel/controller/TravelListControllerTest.java
> #154 
- 예외 처리 및 응답 메시지 개선
- 각 API 엔드포인트에 대해 예외 처리 로직 강화
- 게시물 및 댓글 존재 여부 검증 로직을 메서드로 분리.
- 댓글 목록과 페이지 응답 생성 로직 통합.
> refactor: Comment 관련 예외처리 및 응답 메시지 개선

- src/main/java/swyp/swyp6_team7/comment/domain/Comment.java
- src/main/java/swyp/swyp6_team7/comment/repository/CommentRepository.java
- src/main/java/swyp/swyp6_team7/comment/service/CommentService.java
- src/main/java/swyp/swyp6_team7/community/controller/CommunityController.java
- src/main/java/swyp/swyp6_team7/community/domain/Community.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepository.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepositoryImpl.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityRepository.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityService.java
- src/main/java/swyp/swyp6_team7/member/entity/Users.java
- src/main/java/swyp/swyp6_team7/member/service/MemberDeletedService.java
- src/test/java/swyp/swyp6_team7/comment/controller/CommentControllerTest.java
- src/test/java/swyp/swyp6_team7/comment/service/CommentServiceTest.java
- src/test/java/swyp/swyp6_team7/community/controller/CommunityControllerTest.java
- src/test/java/swyp/swyp6_team7/community/repository/CommunityCustomRepositoryImplTest.java
- src/test/java/swyp/swyp6_team7/community/repository/CommunityRepositoryTest.java
- src/test/java/swyp/swyp6_team7/community/service/CommunityServiceTest.java
> #154 
- 테스트 코드 추가
- community관련 테스트 코드 추가
- comment 관련 테스트 코드 추가
- 기능 개선
- CommunityService의 게시글 상세 조회 로직 개선
- 커뮤니티 목록 조회 시 null 결과에 대한 예외 처리 추가
- 비회원 댓글 목록 조회 시 답글 작성 여부 false 반환 추가
- 리팩토링
- Users 엔티티 및 MemberDeletedService 코드 정리
- JPQL 쿼리 수정 및 테스트
> [TMO-33] 커뮤니티 관련 테스트 코드 추가 및 버그 수정

- src/main/java/swyp/swyp6_team7/global/utils/api/ApiResponse.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ApiResponseException.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ErrorMessage.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ResultType.java
> [TMO-40] 공통 ApiResponse 세팅

- .github/workflows/develop_deploy.yml
- build.gradle
- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
> [TMO-45] allowOrigin 에 moing.io 도메인 추가

- .github/workflows/PR_test.yml
- build.gradle
- settings.gradle
- src/main/java/swyp/swyp6_team7/Swyp6Team7Application.java
- src/main/java/swyp/swyp6_team7/global/config/EmailConfig.java
- src/main/java/swyp/swyp6_team7/global/config/RedisConfig.java
- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
- src/main/java/swyp/swyp6_team7/global/email/EmailSenderProcessor.kt
- src/main/java/swyp/swyp6_team7/global/email/EmailTemplateConfig.java
- src/main/java/swyp/swyp6_team7/global/email/template/EmailMessage.kt
- src/main/java/swyp/swyp6_team7/global/email/template/EmailVerificationCodeMessage.kt
- src/main/java/swyp/swyp6_team7/global/email/template/Template.kt
- src/main/java/swyp/swyp6_team7/global/entity/BaseEntity.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ApiResponse.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ApiResponseException.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ErrorMessage.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ResultType.java
- src/main/java/swyp/swyp6_team7/verify/controller/EmailVerifyController.java
- src/main/java/swyp/swyp6_team7/verify/service/EmailVerifyService.java
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- src/main/resources/templates/email-verification-code.html
> [TMO-39] 이메일 점유인증 Init

- .github/workflows/PR_test.yml
- .github/workflows/develop_deploy.yml
- build.gradle
- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
- src/main/java/swyp/swyp6_team7/global/email/EmailSenderProcessor.java
- src/main/java/swyp/swyp6_team7/global/email/template/EmailMessage.java
- src/main/java/swyp/swyp6_team7/global/email/template/EmailVerificationCodeMessage.java
- src/main/java/swyp/swyp6_team7/global/email/template/Template.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ApiResponse.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ApiResponseException.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ErrorMessage.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ResultType.java
- src/main/java/swyp/swyp6_team7/verify/controller/EmailVerifyController.java
- src/main/java/swyp/swyp6_team7/verify/service/EmailVerifyService.java
- src/main/resources/templates/email-verification-code.html
> [TMO-39] Kotlin -> Java Class 로 다시 변경

- .github/workflows/PR_test.yml
- src/main/java/swyp/swyp6_team7/Swyp6Team7Application.java
- src/main/java/swyp/swyp6_team7/global/config/EmailConfig.java
- src/main/java/swyp/swyp6_team7/global/config/RedisConfig.java
- src/main/java/swyp/swyp6_team7/global/email/EmailTemplateConfig.java
> [TMO-39] Conflict 제거

- src/main/java/swyp/swyp6_team7/verify/service/EmailVerifyService.java
- src/main/resources/templates/email-verification-code.html
> [TMO-39] email 인증 html conflict 수정

- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
- src/main/java/swyp/swyp6_team7/verify/dto/request/EmailVerifySendRequest.java
- src/main/java/swyp/swyp6_team7/verify/service/EmailVerifyService.java
> [TMO-39] moing.io 도메인으로 변경

- src/main/java/swyp/swyp6_team7/auth/controller/TokenController.java
- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
- src/main/java/swyp/swyp6_team7/global/config/WebMvcConfig.java
> [TMO-39] 이메일 기반 회원가입 API 인증 해제

- .github/workflows/deploy.yml
- .github/workflows/develop_deploy.yml
> [TMO-51] alpha/live prod 수정

- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
> [TMO-51] 여행 API 비로그인 호출 가능하도록 수정

- build.gradle
- src/main/java/swyp/swyp6_team7/Inquiry/InquiryType.java
- src/main/java/swyp/swyp6_team7/Inquiry/controller/InquiryController.java
- src/main/java/swyp/swyp6_team7/Inquiry/dto/InquiryRequestDto.java
- src/main/java/swyp/swyp6_team7/Inquiry/service/InquiryService.java
- src/main/java/swyp/swyp6_team7/Inquiry/util/InquiryEmailBuilder.java
- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
- src/main/java/swyp/swyp6_team7/global/exception/GlobalExceptionHandler.java
- src/test/java/swyp/swyp6_team7/inquiry/controller/InquiryContollerTest.java
- src/test/java/swyp/swyp6_team7/inquiry/service/InquiryServiceTest.java
- src/test/resources/application.yml
> [TMO-46] 1:1 문의 구현

- src/main/resources/application.yml
> [TMO-46] smtp application property 수정

- src/main/java/swyp/swyp6_team7/image/s3/S3Uploader.java
- src/main/java/swyp/swyp6_team7/image/service/ImageService.java
- src/main/resources/application.yml
> [TMO-46] profile 용 property 수정

- src/main/resources/application.yml
> [TMO-46] profile bucket 수정

- src/main/java/swyp/swyp6_team7/global/config/TimeConfig.java
- src/main/java/swyp/swyp6_team7/notification/repository/NotificationRepository.java
- src/main/java/swyp/swyp6_team7/notification/service/NotificationDeleteService.java
- src/test/java/swyp/swyp6_team7/notification/repository/NotificationRepositoryTest.java
- src/test/java/swyp/swyp6_team7/notification/service/NotificationDeleteServiceTest.java
Notification을 일괄 삭제하는 스케줄러
* 매일 새벽 2시에 실행
* 생성된 지 45일 이상 된 알림이 대상
> [TMO-52] Notification 삭제 스케줄러 기능 구현

- src/main/java/swyp/swyp6_team7/global/exception/GlobalExceptionHandler.java
- src/main/java/swyp/swyp6_team7/profile/controller/ProfileController.java
- src/main/java/swyp/swyp6_team7/profile/dto/ProfileViewResponse.java
> [TMO-55] 유저 Profile 응답에 소셜로그인 여부 포함

- src/main/java/swyp/swyp6_team7/comment/service/CommentService.java
- src/main/java/swyp/swyp6_team7/companion/repository/CompanionRepository.java
- src/main/java/swyp/swyp6_team7/likes/service/LikeService.java
- src/main/java/swyp/swyp6_team7/notification/dto/CommunityCommentNotificationDto.java
- src/main/java/swyp/swyp6_team7/notification/dto/CommunityPostLikeNotificationDto.java
- src/main/java/swyp/swyp6_team7/notification/entity/CommunityCommentNotification.java
- src/main/java/swyp/swyp6_team7/notification/entity/CommunityPostLikeNotification.java
- src/main/java/swyp/swyp6_team7/notification/entity/NotificationMessageType.java
- src/main/java/swyp/swyp6_team7/notification/entity/TravelCommentNotification.java
- src/main/java/swyp/swyp6_team7/notification/repository/NotificationRepository.java
- src/main/java/swyp/swyp6_team7/notification/service/CommentNotificationService.java
- src/main/java/swyp/swyp6_team7/notification/service/LikeNotificationService.java
- src/main/java/swyp/swyp6_team7/notification/service/NotificationService.java
- src/main/java/swyp/swyp6_team7/notification/util/NotificationMaker.java
- src/test/java/swyp/swyp6_team7/comment/service/CommentServiceTest.java
- src/test/java/swyp/swyp6_team7/companion/repository/CompanionRepositoryTest.java
- src/test/java/swyp/swyp6_team7/notification/repository/NotificationRepositoryTest.java
- src/test/java/swyp/swyp6_team7/notification/service/CommentNotificationServiceTest.java
- src/test/java/swyp/swyp6_team7/notification/service/LikeNotificationServiceTest.java
- src/test/java/swyp/swyp6_team7/notification/service/NotificationServiceTest.java
> [TMO-54] 커뮤니티 알림 구현

- src/main/java/swyp/swyp6_team7/auth/controller/LoginController.java
- src/main/java/swyp/swyp6_team7/auth/controller/LogoutController.java
- src/main/java/swyp/swyp6_team7/auth/controller/TokenController.java
- src/main/java/swyp/swyp6_team7/auth/service/JwtBlacklistService.java
- src/main/java/swyp/swyp6_team7/auth/service/LoginService.java
- src/main/java/swyp/swyp6_team7/auth/service/TokenService.java
- src/main/java/swyp/swyp6_team7/member/controller/MemberController.java
- src/test/java/swyp/swyp6_team7/auth/controller/LoginControllerTest.java
- src/test/java/swyp/swyp6_team7/auth/controller/LogoutControllerTest.java
- src/test/java/swyp/swyp6_team7/auth/controller/TokenControllerTest.java
- src/test/java/swyp/swyp6_team7/auth/service/LoginServiceTest.java
- src/test/java/swyp/swyp6_team7/auth/service/TokenServiceTest.java
- token rotaion 방식 적용
- Redis에 Refresh token 저장 및 관리
- 회원 탈퇴 시 httpOnly 쿠키에 남은 Refresh Token 처리
> [TMO-48] JWT 관리 로직 수정

- src/main/java/swyp/swyp6_team7/auth/controller/GoogleController.java
- src/main/java/swyp/swyp6_team7/auth/controller/KakaoController.java
- src/main/java/swyp/swyp6_team7/auth/controller/LoginController.java
- src/main/java/swyp/swyp6_team7/auth/controller/LogoutController.java
- src/main/java/swyp/swyp6_team7/auth/controller/NaverController.java
- src/main/java/swyp/swyp6_team7/auth/controller/PasswordController.java
- src/main/java/swyp/swyp6_team7/auth/controller/SocialLoginController.java
- src/main/java/swyp/swyp6_team7/auth/controller/TokenController.java
- src/main/java/swyp/swyp6_team7/auth/dto/LoginResponse.java
- src/main/java/swyp/swyp6_team7/auth/dto/SocialUserSignUpResponse.java
- src/main/java/swyp/swyp6_team7/auth/dto/UserInfoDto.java
- src/main/java/swyp/swyp6_team7/auth/service/GoogleService.java
- src/main/java/swyp/swyp6_team7/auth/service/KakaoService.java
- src/main/java/swyp/swyp6_team7/auth/service/NaverService.java
- src/main/java/swyp/swyp6_team7/global/exception/GlobalExceptionHandler.java
- src/main/java/swyp/swyp6_team7/global/exception/MoingAuthenticationException.java
- src/main/java/swyp/swyp6_team7/global/utils/api/ResultType.java
- src/test/java/swyp/swyp6_team7/auth/controller/LoginControllerTest.java
- src/test/java/swyp/swyp6_team7/auth/controller/LogoutControllerTest.java
- src/test/java/swyp/swyp6_team7/auth/controller/TokenControllerTest.java
> [TMO-56] API Response Auth에도 적용

- .github/workflows/develop_deploy.yml
- src/main/java/swyp/swyp6_team7/auth/filter/DevAuthenticationFilter.java
- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
- src/test/java/swyp/swyp6_team7/auth/service/JwtBlacklistServiceTest.java
- src/test/java/swyp/swyp6_team7/member/controller/MemberControllerTest.java
- src/test/java/swyp/swyp6_team7/member/service/MemberBlockServiceTest.java
- src/test/resources/application.yml
> [TMO-61] 알파환경 Whitelist origin 기반 구현

- src/main/java/swyp/swyp6_team7/Plan/controller/PlanController.java
- src/main/java/swyp/swyp6_team7/Plan/dto/PlanDetailDto.java
- src/main/java/swyp/swyp6_team7/Plan/dto/request/AllPlanUpdateRequest.java
- src/main/java/swyp/swyp6_team7/Plan/dto/request/PlanCreateRequest.java
- src/main/java/swyp/swyp6_team7/Plan/dto/request/PlanUpdateRequest.java
- src/main/java/swyp/swyp6_team7/Plan/dto/request/SpotRequest.java
- src/main/java/swyp/swyp6_team7/Plan/dto/response/PlanResponse.java
- src/main/java/swyp/swyp6_team7/Plan/entity/Plan.java
- src/main/java/swyp/swyp6_team7/Plan/entity/Spot.java
- src/main/java/swyp/swyp6_team7/Plan/repository/PlanRepository.java
- src/main/java/swyp/swyp6_team7/Plan/repository/SpotRepository.java
- src/main/java/swyp/swyp6_team7/Plan/service/PlanService.java
- src/main/java/swyp/swyp6_team7/travel/domain/Travel.java
- src/main/java/swyp/swyp6_team7/travel/dto/request/TravelCreateRequest.java
- src/main/java/swyp/swyp6_team7/travel/dto/request/TravelUpdateRequest.java
- src/main/java/swyp/swyp6_team7/travel/repository/TravelRepository.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
- src/test/java/swyp/swyp6_team7/Plan/service/PlanServiceTest.java
- src/test/java/swyp/swyp6_team7/travel/service/TravelServiceTest.java
> [TMO-60] 여행 일정 CRUD 구현 및 여행 API 수정

- src/main/java/swyp/swyp6_team7/travel/controller/TravelController.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelHomeController.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelSearchController.java
- src/main/java/swyp/swyp6_team7/travel/dto/TravelRecommendForMemberDto.java
- src/main/java/swyp/swyp6_team7/travel/dto/TravelRecommendForNonMemberDto.java
- src/main/java/swyp/swyp6_team7/travel/dto/response/TravelRecentDto.java
- src/main/java/swyp/swyp6_team7/travel/dto/response/TravelRecommendResponse.java
- src/main/java/swyp/swyp6_team7/travel/dto/response/TravelSearchDto.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelHomeService.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelSearchService.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
- src/test/java/swyp/swyp6_team7/travel/controller/TravelHomeControllerTest.java
- src/test/java/swyp/swyp6_team7/travel/service/TravelHomeServiceTest.java
- src/test/java/swyp/swyp6_team7/travel/service/TravelServiceTest.java
> [TMO-63] 여행 목록 조회 응답 데이터 추가

- src/main/java/swyp/swyp6_team7/comment/repository/CommentRepository.java
- src/main/java/swyp/swyp6_team7/plan/repository/PlanRepository.java
- src/main/java/swyp/swyp6_team7/plan/repository/SpotRepository.java
- src/main/java/swyp/swyp6_team7/plan/service/PlanService.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelController.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
- src/test/java/swyp/swyp6_team7/travel/service/TravelServiceTest.java
> [TMO-57] 여행 삭제 기능 버그 수정

- src/main/java/swyp/swyp6_team7/auth/controller/LoginController.java
- src/main/java/swyp/swyp6_team7/auth/controller/SocialLoginController.java
- src/main/java/swyp/swyp6_team7/auth/controller/TokenController.java
- src/main/java/swyp/swyp6_team7/auth/dto/LoginResponse.java
- src/main/java/swyp/swyp6_team7/auth/service/LoginFacade.java
- src/main/java/swyp/swyp6_team7/auth/service/TokenService.java
- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
- src/main/java/swyp/swyp6_team7/global/config/WebMvcConfig.java
- src/main/java/swyp/swyp6_team7/member/dto/UserBlockDetailResponse.java
- src/main/java/swyp/swyp6_team7/member/service/MemberBlockService.java
- src/main/resources/application.yml
- src/test/java/swyp/swyp6_team7/auth/service/TokenServiceTest.java
- src/test/resources/application.yml
> [TMO-64] 정지유저면 redirectUrl 응답하도록 수정

- src/main/java/swyp/swyp6_team7/auth/controller/SocialLoginController.java
- src/main/java/swyp/swyp6_team7/auth/service/LoginFacade.java
- src/main/java/swyp/swyp6_team7/auth/service/TokenService.java
- src/main/java/swyp/swyp6_team7/location/repository/LocationRepository.java
- src/test/java/swyp/swyp6_team7/auth/service/JwtBlacklistServiceTest.java
- src/test/java/swyp/swyp6_team7/bookmark/controller/BookmarkControllerTest.java
- src/test/java/swyp/swyp6_team7/global/IntegrationTest.java
> [TMO-59] 소셜 로그인 로그인 에러 수정

- src/main/java/swyp/swyp6_team7/auth/service/LoginFacade.java
- src/main/java/swyp/swyp6_team7/auth/service/TokenService.java
- src/main/java/swyp/swyp6_team7/https/HealthController.java
- src/main/java/swyp/swyp6_team7/image/controller/ImageProfileController.java
- src/main/java/swyp/swyp6_team7/image/util/S3KeyHandler.java
- src/test/java/swyp/swyp6_team7/config/RedisContainerConfig.java
- src/test/java/swyp/swyp6_team7/global/IntegrationTest.java
- src/test/java/swyp/swyp6_team7/image/controller/ImageProfileControllerTest.java
- src/test/resources/application.yml
> [TMO-65] ImageProfile API 응답 수정

- .github/workflows/develop_deploy.yml
- src/main/java/swyp/swyp6_team7/community/controller/CommunityController.java
- src/main/java/swyp/swyp6_team7/community/dto/response/CommunitySearchCondition.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityCustomRepositoryImpl.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityService.java
- src/main/java/swyp/swyp6_team7/notification/service/LikeNotificationService.java
- src/test/java/swyp/swyp6_team7/auth/service/TokenServiceTest.java
- src/test/java/swyp/swyp6_team7/bookmark/controller/BookmarkControllerTest.java
- src/test/java/swyp/swyp6_team7/companion/service/CompanionServiceTest.java
- src/test/java/swyp/swyp6_team7/enrollment/controller/EnrollmentControllerTest.java
- src/test/java/swyp/swyp6_team7/global/IntegrationTest.java
- src/test/java/swyp/swyp6_team7/image/controller/ImageCommunityControllerTest.java
- src/test/java/swyp/swyp6_team7/image/controller/ImageProfileControllerTest.java
- src/test/java/swyp/swyp6_team7/image/util/S3KeyHandlerTest.java
- src/test/java/swyp/swyp6_team7/notification/service/CommentNotificationServiceTest.java
- src/test/java/swyp/swyp6_team7/notification/service/LikeNotificationServiceTest.java
- src/test/java/swyp/swyp6_team7/travel/controller/TravelControllerTest.java
- src/test/java/swyp/swyp6_team7/travel/service/TravelSearchServiceTest.java
- src/test/resources/init.sql
> [TMO-66] 커뮤니티 전체항목 조회 수정

- src/main/java/swyp/swyp6_team7/global/config/SecurityConfig.java
> [TMO-66] 내 계정차단 조회내역 확인 authorize 수정

- src/main/java/swyp/swyp6_team7/member/entity/Users.java
- src/main/java/swyp/swyp6_team7/verify/service/EmailVerifyService.java
- src/main/resources/templates/email-verification-code.html
> [TMO-69] 이메일 인증번호 템플릿 변경

- src/main/java/swyp/swyp6_team7/image/util/S3KeyHandler.java
- src/test/java/swyp/swyp6_team7/image/util/S3KeyHandlerTest.java
> [TMO-70] S3KeyHandler 필드 초기화 오류 수정

- src/main/java/swyp/swyp6_team7/community/controller/CommunityController.java
- src/main/java/swyp/swyp6_team7/community/repository/CommunityRepository.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityService.java
- src/main/java/swyp/swyp6_team7/community/service/CommunityViewCountService.java
- src/main/java/swyp/swyp6_team7/companion/dto/CompanionInfoDto.java
- src/main/java/swyp/swyp6_team7/travel/controller/TravelCompanionController.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
- src/test/java/swyp/swyp6_team7/community/service/CommunityServiceTest.java
- src/test/java/swyp/swyp6_team7/enrollment/controller/EnrollmentControllerTest.java
> [TMO-67] 커뮤니티 조회수 로직 변경

- src/main/java/swyp/swyp6_team7/image/service/ImageProfileService.java
- src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
> [TMO-57] 여행 조회 디폴트 프로필 이미지 URL 수정

- src/main/java/swyp/swyp6_team7/member/dto/UserReportRequest.java
- src/main/java/swyp/swyp6_team7/member/service/MemberBlockService.java
- src/test/java/swyp/swyp6_team7/member/controller/MemberBlockControllerTest.java
- src/test/java/swyp/swyp6_team7/member/controller/MemberControllerTest.java
> [TMO-64] 신고하기 테스트 추가

- src/main/java/swyp/swyp6_team7/auth/controller/GoogleController.java
- src/main/java/swyp/swyp6_team7/auth/controller/KakaoController.java
- src/main/java/swyp/swyp6_team7/auth/controller/NaverController.java
- src/main/java/swyp/swyp6_team7/auth/dto/UserInfoDto.java
- src/main/java/swyp/swyp6_team7/auth/service/GoogleService.java
- src/main/java/swyp/swyp6_team7/auth/service/KakaoService.java
- src/main/java/swyp/swyp6_team7/auth/service/NaverService.java
- src/main/java/swyp/swyp6_team7/member/controller/MemberController.java
- src/main/java/swyp/swyp6_team7/member/service/MemberService.java
> [TMO-72] Social 회원가입 응답 수정

- src/main/java/swyp/swyp6_team7/auth/controller/GoogleController.java
- src/main/java/swyp/swyp6_team7/auth/controller/KakaoController.java
- src/main/java/swyp/swyp6_team7/auth/controller/NaverController.java
- src/main/java/swyp/swyp6_team7/auth/dto/UserInfoDto.java
- src/main/java/swyp/swyp6_team7/auth/service/GoogleService.java
- src/main/java/swyp/swyp6_team7/auth/service/KakaoService.java
- src/main/java/swyp/swyp6_team7/auth/service/NaverService.java
- src/main/java/swyp/swyp6_team7/member/controller/MemberController.java
- src/main/java/swyp/swyp6_team7/member/service/MemberService.java
Reverts SWYP6-Team7/backend#222
> Revert "[TMO-72] Social 회원가입 응답 수정"

- src/main/java/swyp/swyp6_team7/auth/controller/LogoutController.java
- src/main/java/swyp/swyp6_team7/auth/jwt/JwtFilter.java
- src/main/java/swyp/swyp6_team7/auth/service/LogoutService.java
> [TMO-71] 로그아웃 시 세션 무효화 처리 추가

- src/test/java/swyp/swyp6_team7/auth/jwt/JwtFilterTest.java
> [TMO-71] jwtFilter 테스트 코드 수정

- src/main/java/swyp/swyp6_team7/auth/jwt/JwtProvider.java
- src/main/java/swyp/swyp6_team7/auth/service/TokenService.java
> [TMO-71] JwtProvider 예외처리 강화 및 토큰 검증 추가

- src/main/java/swyp/swyp6_team7/auth/jwt/JwtFilter.java
- src/main/java/swyp/swyp6_team7/member/controller/MemberController.java
- src/main/java/swyp/swyp6_team7/member/repository/SocialUserRepository.java
- src/main/java/swyp/swyp6_team7/member/service/MemberDeletedService.java
- src/test/java/swyp/swyp6_team7/member/service/DeletedMemberServiceTest.java
> [TMO-73] 소셜로그인 유저 탈퇴처리
